#!/bin/sh
echo "▶️ Running pre-commit checks..."

./gradlew ktlint
EXIT_CODE=$?

if [ ${EXIT_CODE} -ne 0 ]; then
    echo "😵 Pre Commit checks failed. Please fix the above issues before committing"
    exit ${EXIT_CODE}
else
    echo "✅ Pre Commit checks passed, no problems found"
    exit 0
fi